server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
zuul:
  prefix: /glarimy
  routes:
    book-service:
      path: /library/**
      serviceId: BOOK-SERVICE
    static:
      path: /home/**
spring:
  application:
    name: zuul-server